version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/pull_docker_image.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/run_container.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root